plugins {
    id 'java'
    id 'org.springframework.boot' version '3.2.4'
    id 'io.spring.dependency-management' version '1.1.4'
}

group = 'com.fims'
version = '0.0.1-SNAPSHOT'
java {
    sourceCompatibility = '17'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    
    // SOAP 연동을 위한 의존성
    implementation 'org.springframework.boot:spring-boot-starter-web-services'
    implementation 'org.apache.cxf:cxf-rt-frontend-jaxws:4.0.3'
    implementation 'org.apache.cxf:cxf-rt-transports-http:4.0.3'
    
    // JAXB 런타임 (Jakarta EE 10 호환)
    implementation 'org.glassfish.jaxb:jaxb-runtime:4.0.4'
    implementation 'com.sun.xml.bind:jaxb-xjc:4.0.4'
    implementation 'jakarta.xml.bind:jakarta.xml.bind-api:4.0.1'
    
    // Web Service Marshalling 지원
    implementation 'org.springframework:spring-oxm'
    
    // MQ 연동을 위한 의존성 (ActiveMQ)
    implementation 'org.springframework.boot:spring-boot-starter-activemq'
    
    // Batch 작업을 위한 의존성
    implementation 'org.springframework.boot:spring-boot-starter-batch'
    
    // SFTP연동을 위한 라이브러리 (Apache Commons Net & JSch)
    implementation 'commons-net:commons-net:3.10.0'
    implementation 'com.github.mwiede:jsch:0.2.17'
    
    // JSON 파싱용 Jackson
    implementation 'com.fasterxml.jackson.core:jackson-databind'
    
    // 시연용 H2 DB (인메모리)
    runtimeOnly 'com.h2database:h2'
    
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.security:spring-security-test'
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

tasks.named('test') {
    useJUnitPlatform()
}

tasks.named('bootJar') {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
